version: '3.8'
services:
    laravel.test:
        build:
            context: .
            dockerfile: Dockerfile
        image: stocznia-app
        container_name: stocznia-app
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        ports:
            - '8000:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            APP_ENV: local
            APP_DEBUG: true
            APP_URL: http://localhost:8000
            DB_CONNECTION: sqlite
        networks:
            - stocznia-network

networks:
    stocznia-network:
        driver: bridge
